apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bot.name" . }}-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: postgres:14
          command:
            - "sh"
            - "-c"
            - |
              until pg_isready -h {{ include "bot.name" . }}-postgres-service.{{ .Release.Namespace }}.svc.cluster.local -p 5432;
              do echo waiting for postgres;
              sleep 2;
              done;
      containers:
        - name: {{ .Chart.Name }}-nonebot-migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 14 }}
          image: "{{ .Values.bot.image.repo }}:{{ .Values.bot.image.tag }}"
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          command: ["/bin/sh", "-c", "python ./scripts/database.py upgrade"]
          env:
            - name: ENVIRONMENT
              value: prod
            - name: HOST
              value: "0.0.0.0"
            {{- range $key, $value := .Values.bot.config }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
