version: "3"
services:
  redis:
    image: redis:7
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    command: ["sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD}"]
    volumes:
      - bot_redis_data:/data
    restart: always
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
      - TZ=Asia/Shanghai
    volumes:
      - bot_postgres_data:/var/lib/postgresql/data
    restart: always
  go-cqhttp:
    image: ghcr.io/mrs4s/go-cqhttp:latest
    volumes:
      - "./bot:/data"
    depends_on:
      - nonebot
    restart: always
  nonebot:
    # image: cscs181/qq-github-bot:latest # docker hub
    # image: ghcr.io/cscs181/qq-github-bot:latest # github image mirror
    build: . # use "build" instead of "image" if you want to build the image yourself
    environment:
      - ENVIRONMENT=prod
      - HOST=$HOST
      - PORT=$PORT
      - MAX_WORKERS=1 # maximum workers
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    restart: always
volumes:
  bot_redis_data: {}
  bot_postgres_data: {}
