[tool.poetry]
name = "qq-github-bot"
version = "0.1.4"
description = "GitHub Bot for QQ"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.7.2"
httpx = "^0.18.0"
Jinja2 = "^3.0.0"
unidiff = "^0.6.0"
humanize = "^3.5.0"
pydantic = "^1.8.1"
Markdown = "^3.3.4"
sentry-sdk = "^1.0.0"
playwright = "^1.9.2"
typing-extensions = "^3.7.4"
nonebot2 = "^2.0.0-alpha.15"
nonebot-adapter-cqhttp = "^2.0.0-alpha.15"
redis = {version = "^3.5.3", extras = ["hiredis"]}

[tool.poetry.dev-dependencies]
isort = "^5.9.3"
black = "^21.8b0"
# nonebot-plugin-test = "^0.2.0"
nb-cli = {version = "^0.5.0", extras = ["deploy"]}

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[tool.black]
line-length = 80
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 80
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = "typing_extensions"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
