[tool.poetry]
name = "qq-github-bot"
version = "0.1.0"
description = "GitHub Bot for QQ"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
psutil = "^5.7.2"
nb-cli = "^0.2.0"
sentry-sdk = "^0.19.4"
nonebot2 = "^2.0.0-alpha.8"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"
nonebot-test = "^0.1.0"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
