[tool.poetry]
name = "qq-github-bot"
version = "0.1.1"
description = "GitHub Bot for QQ"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.3"
psutil = "^5.7.2"
httpx = "^0.17.0"
pydantic = "^1.8.1"
Markdown = "^3.3.4"
sentry-sdk = "^1.0.0"
playwright = "^1.9.2"
typing-extensions = "^3.7.4"
nonebot2 = "=2.0.0a13.post1"
nonebot-adapter-cqhttp = "^2.0.0-alpha.12"
redis = {version = "^3.5.3", extras = ["hiredis"]}
Jinja2 = "^3.0.0"
humanize = "^3.5.0"
unidiff = "^0.6.0"

[tool.poetry.dev-dependencies]
yapf = "^0.30.0"
nonebot-plugin-test = "^0.2.0"
nb-cli = {version = "^0.4.1", extras = ["deploy"]}

[nonebot.plugins]
plugins = ["nonebot_plugin_test"]
plugin_dirs = ["src/plugins"]

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
