[tool.poetry]
name = "qq-github-bot"
version = "0.2.0"
description = "GitHub Bot for QQ"
authors = ["yanyongyu <yanyongyu_1@126.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
psutil = "^5.7.2"
httpx = "^0.21.0"
Jinja2 = "^3.0.0"
unidiff = "^0.7.0"
humanize = "^3.5.0"
pydantic = "^1.9.0"
Markdown = "^3.3.4"
sentry-sdk = "^1.0.0"
playwright = "^1.17.2"
nonebot2 = "^2.0.0-beta.2"
typing-extensions = "^4.0.0"
nonebot-adapter-onebot = "^2.0.0-beta.1"
redis = { version = "^4.0.0", extras = ["hiredis"] }

[tool.poetry.dev-dependencies]
isort = "^5.9.3"
black = "^21.8b0"
nb-cli = "^0.6.0"
nonebug = "^0.2.0"

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[tool.black]
line-length = 80
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 80
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = "typing_extensions"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
