apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "bot.name" . }}-redis-pv
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: {{ .Values.redis.persistencePath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.redis.nodeHostName }}
