apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bot.name" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
